import type { NextPage } from "next";
import Head from "next/head";
import { Button, Heading } from "@chakra-ui/react";
import { useSupabaseClient, useUser } from "@supabase/auth-helpers-react";

const Home: NextPage = () => {
  const supabase = useSupabaseClient();
  const user = useUser();

  const login = async () => {
    await supabase.auth.signInWithOAuth({
      provider: "google",
    });
  };

  const logout = async () => {
    await supabase.auth.signOut();
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>Hello {user ? user.id : "World"}</Heading>
        <Button colorScheme="teal" onClick={login}>
          Login
        </Button>
        <Button colorScheme="red" onClick={logout}>
          Logout
        </Button>
      </main>
    </>
  );
};

export default Home;
